github:
  description: "Apache Spark Connect Client for Golang"
  homepage: https://spark.apache.org/
  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: true
  features:
    # Enable the "Issues" tab
    issues: true
    # Enable the "Projects" tab
    projects: true

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  pullrequests: reviews@spark.apache.org
  issues: reviews@spark.apache.org
  commits: commits@spark.apache.org

